package client

import (
	"context"
	"testing"

	discovery "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3"
)

// Mock handler for testing
type mockHandler struct {
	updateCalled bool
	removeCalled bool
	updateError  error
	removeError  error
}

func (m *mockHandler) Update(ctx context.Context, resources []*discovery.Resource) error {
	m.updateCalled = true
	return m.updateError
}

func (m *mockHandler) Remove(ctx context.Context, resourceNames []string) error {
	m.removeCalled = true
	return m.removeError
}

func TestNewADSClient_ValidConfig(t *testing.T) {
	handler := &mockHandler{}
	cfg := Config{
		ServerAddress:        "localhost:9978",
		Namespace:            "test-ns",
		GatewayName:          "test-gateway",
		Token:                "test-token",
		ResourceTypeHandlers: ResourceTypeStore{"test.type": handler},
	}

	client, err := NewADSClient(cfg)
	if err != nil {
		t.Fatalf("Expected no error, got: %v", err)
	}

	if client == nil {
		t.Fatal("Expected client to be non-nil")
	}

	if client.token != "test-token" {
		t.Errorf("Expected token 'test-token', got '%s'", client.token)
	}

	if client.nodeInfo == nil {
		t.Fatal("Expected nodeInfo to be non-nil")
	}

	// Verify node metadata
	expectedRole := "test-ns~test-gateway"
	if client.nodeInfo.Metadata.Fields["role"].GetStringValue() != expectedRole {
		t.Errorf("Expected role '%s', got '%s'", expectedRole, client.nodeInfo.Metadata.Fields["role"].GetStringValue())
	}

	if client.nodeInfo.Metadata.Fields["NAMESPACE"].GetStringValue() != "test-ns" {
		t.Errorf("Expected namespace 'test-ns', got '%s'", client.nodeInfo.Metadata.Fields["NAMESPACE"].GetStringValue())
	}

	if client.nodeInfo.Metadata.Fields["GATEWAY"].GetStringValue() != "test-gateway" {
		t.Errorf("Expected gateway 'test-gateway', got '%s'", client.nodeInfo.Metadata.Fields["GATEWAY"].GetStringValue())
	}
}

func TestNewADSClient_WithCustomName(t *testing.T) {
	cfg := Config{
		ServerAddress:        "localhost:9978",
		Namespace:            "test-ns",
		GatewayName:          "test-gateway",
		Name:                 "custom-name",
		Token:                "test-token",
		ResourceTypeHandlers: ResourceTypeStore{},
	}

	client, err := NewADSClient(cfg)
	if err != nil {
		t.Fatalf("Expected no error, got: %v", err)
	}

	if client.nodeInfo.Metadata.Fields["NAME"].GetStringValue() != "custom-name" {
		t.Errorf("Expected name 'custom-name', got '%s'", client.nodeInfo.Metadata.Fields["NAME"].GetStringValue())
	}

	expectedNodeID := "agentgateway~custom-name~custom-name.test-ns~test-ns.svc.cluster.local"
	if client.nodeInfo.Id != expectedNodeID {
		t.Errorf("Expected node ID '%s', got '%s'", expectedNodeID, client.nodeInfo.Id)
	}
}

func TestNewADSClient_AutoGeneratedName(t *testing.T) {
	cfg := Config{
		ServerAddress:        "localhost:9978",
		Namespace:            "test-ns",
		GatewayName:          "test-gateway",
		Token:                "test-token",
		ResourceTypeHandlers: ResourceTypeStore{},
	}

	client1, err := NewADSClient(cfg)
	if err != nil {
		t.Fatalf("Expected no error, got: %v", err)
	}

	client2, err := NewADSClient(cfg)
	if err != nil {
		t.Fatalf("Expected no error, got: %v", err)
	}

	// Auto-generated names should be different (random suffix)
	name1 := client1.nodeInfo.Metadata.Fields["NAME"].GetStringValue()
	name2 := client2.nodeInfo.Metadata.Fields["NAME"].GetStringValue()

	if name1 == name2 {
		t.Errorf("Expected different auto-generated names, both are '%s'", name1)
	}

	// Both should start with gateway name
	if len(name1) <= len("test-gateway") {
		t.Errorf("Expected auto-generated name to have suffix, got '%s'", name1)
	}
}

func TestNewADSClient_MissingServerAddress(t *testing.T) {
	cfg := Config{
		Namespace:            "test-ns",
		GatewayName:          "test-gateway",
		Token:                "test-token",
		ResourceTypeHandlers: ResourceTypeStore{},
	}

	_, err := NewADSClient(cfg)
	if err == nil {
		t.Fatal("Expected error for missing server address")
	}

	expectedMsg := "serveraddress, namespace, gatewayname and token are required"
	if err.Error() != expectedMsg {
		t.Errorf("Expected error '%s', got '%s'", expectedMsg, err.Error())
	}
}

func TestNewADSClient_MissingNamespace(t *testing.T) {
	cfg := Config{
		ServerAddress:        "localhost:9978",
		GatewayName:          "test-gateway",
		Token:                "test-token",
		ResourceTypeHandlers: ResourceTypeStore{},
	}

	_, err := NewADSClient(cfg)
	if err == nil {
		t.Fatal("Expected error for missing namespace")
	}
}

func TestNewADSClient_MissingGatewayName(t *testing.T) {
	cfg := Config{
		ServerAddress:        "localhost:9978",
		Namespace:            "test-ns",
		Token:                "test-token",
		ResourceTypeHandlers: ResourceTypeStore{},
	}

	_, err := NewADSClient(cfg)
	if err == nil {
		t.Fatal("Expected error for missing gateway name")
	}
}

func TestNewADSClient_MissingToken(t *testing.T) {
	cfg := Config{
		ServerAddress:        "localhost:9978",
		Namespace:            "test-ns",
		GatewayName:          "test-gateway",
		ResourceTypeHandlers: ResourceTypeStore{},
	}

	_, err := NewADSClient(cfg)
	if err == nil {
		t.Fatal("Expected error for missing token")
	}
}

func TestNewADSClient_InvalidServerAddress(t *testing.T) {
	testCases := []struct {
		name    string
		address string
	}{
		{"no port", "localhost"},
		{"invalid format", "not-a-valid-address"},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			cfg := Config{
				ServerAddress:        tc.address,
				Namespace:            "test-ns",
				GatewayName:          "test-gateway",
				Token:                "test-token",
				ResourceTypeHandlers: ResourceTypeStore{},
			}

			_, err := NewADSClient(cfg)
			if err == nil {
				t.Fatalf("Expected error for invalid server address '%s'", tc.address)
			}
		})
	}
}

func TestNewADSClient_ValidServerAddresses(t *testing.T) {
	testCases := []string{
		"localhost:9978",
		"127.0.0.1:9978",
		"agentgateway.example.com:9978",
		"[::1]:9978",
		"example.com:443",
	}

	for _, addr := range testCases {
		t.Run(addr, func(t *testing.T) {
			cfg := Config{
				ServerAddress:        addr,
				Namespace:            "test-ns",
				GatewayName:          "test-gateway",
				Token:                "test-token",
				ResourceTypeHandlers: ResourceTypeStore{},
			}

			_, err := NewADSClient(cfg)
			if err != nil {
				t.Errorf("Expected no error for valid address '%s', got: %v", addr, err)
			}
		})
	}
}

func TestNewADSClient_NodeIDFormat(t *testing.T) {
	cfg := Config{
		ServerAddress:        "localhost:9978",
		Namespace:            "my-namespace",
		GatewayName:          "my-gateway",
		Name:                 "my-name",
		Token:                "test-token",
		ResourceTypeHandlers: ResourceTypeStore{},
	}

	client, err := NewADSClient(cfg)
	if err != nil {
		t.Fatalf("Expected no error, got: %v", err)
	}

	expectedNodeID := "agentgateway~my-name~my-name.my-namespace~my-namespace.svc.cluster.local"
	if client.nodeInfo.Id != expectedNodeID {
		t.Errorf("Expected node ID '%s', got '%s'", expectedNodeID, client.nodeInfo.Id)
	}
}

func TestNewADSClient_RoleFormat(t *testing.T) {
	cfg := Config{
		ServerAddress:        "localhost:9978",
		Namespace:            "production",
		GatewayName:          "api-gateway",
		Token:                "test-token",
		ResourceTypeHandlers: ResourceTypeStore{},
	}

	client, err := NewADSClient(cfg)
	if err != nil {
		t.Fatalf("Expected no error, got: %v", err)
	}

	expectedRole := "production~api-gateway"
	actualRole := client.nodeInfo.Metadata.Fields["role"].GetStringValue()
	if actualRole != expectedRole {
		t.Errorf("Expected role '%s', got '%s'", expectedRole, actualRole)
	}
}

func TestResourceTypeStore(t *testing.T) {
	handler1 := &mockHandler{}
	handler2 := &mockHandler{}

	store := ResourceTypeStore{
		"type.googleapis.com/istio.workload.Address":             handler1,
		"type.googleapis.com/agentgateway.dev.resource.Resource": handler2,
	}

	if len(store) != 2 {
		t.Errorf("Expected store length 2, got %d", len(store))
	}

	if store["type.googleapis.com/istio.workload.Address"] != handler1 {
		t.Error("Expected handler1 for Address type")
	}

	if store["type.googleapis.com/agentgateway.dev.resource.Resource"] != handler2 {
		t.Error("Expected handler2 for Resource type")
	}
}
