apiVersion: gateway.networking.k8s.io/v1
date: "2026-03-22T10:20:13-03:00"
gatewayAPIChannel: UNDEFINED
gatewayAPIVersion: UNDEFINED
implementation:
  contact:
  - ""
  organization: Ricardo
  project: Ricardo
  url: https://nothing.tld
  version: 0.0.1
kind: ConformanceReport
mode: gateway
profiles:
- core:
    failedTests:
    - HTTPRouteHeaderMatching
    - HTTPRouteHostnameIntersection
    - HTTPRouteInvalidBackendRefUnknownKind
    - HTTPRouteInvalidCrossNamespaceBackendRef
    - HTTPRouteInvalidNonExistentBackendRef
    - HTTPRouteInvalidReferenceGrant
    - HTTPRouteListenerHostnameMatching
    - HTTPRouteMatching
    - HTTPRouteMatchingAcrossRoutes
    - HTTPRoutePartiallyInvalidViaInvalidReferenceGrant
    - HTTPRouteRedirectHostAndStatus
    - HTTPRouteReferenceGrant
    - HTTPRouteRequestHeaderModifier
    - HTTPRouteWeight
    result: failure
    statistics:
      Failed: 14
      Passed: 19
      Skipped: 0
  name: GATEWAY-HTTP
  summary: Core tests failed with 14 test failures.
