pid /tmp/nginx/nginx.pid;

error_log stderr;

events {}

http {
    # Include all endpoint upstream configurations
    include endpoints/*.conf;
    # Include all server block configurations
    include servers/*.conf;
}

